BlackJack.Web/Controllers/GameController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using BlackJack.ViewModels.Views.GameViews;
using System;
using BlackJack.BusinessLogic.Enums;
using BlackJack.BusinessLogic.Services.Interfaces;

namespace BlackJack.Web.Controllers
{
    public class GameController : Controller
    {
        private IGameService _gameService;
        public GameController(IGameService gameService)
        {
            _gameService = gameService;
        }

        public async Task<ActionResult> StartGame()
        {
            StartGameGameView startGame = await _gameService.StartGame();
            return View(startGame);
        }

        [HttpPost]
        public async Task<ActionResult> CreateGame(RequestCreateGameGameView requestData)
        {
            if (ModelState.IsValid)
            {
                ResponseCreateGameGameView responseData = await _gameService.CreateGame(requestData);
                if (responseData.GameId != 0)
                {
                    return RedirectToAction("CurrentGame", new { id = responseData.GameId, param = GetActionInGame.FirstRound });
                }
            }
            return RedirectToAction("StartGame", "Game");
        }

        public async Task<ActionResult> CurrentGame(int id, GetActionInGame param)
        {
            ModelState.Clear();

            CurrentGameGameView round = await _gameService.CurrentGame(id, param);

            if ((round.IsDealerTakes && (param == GetActionInGame.FirstRound || param == GetActionInGame.NextRound)) || !round.IsDealerTakes && param == GetActionInGame.DealerTakes)
            {
                round = await _gameService.CurrentGame(id, GetActionInGame.DealerTakes);
                return View("_GameEnd", round);
            }

            if (!round.IsDealerTakes && param == GetActionInGame.FirstRound)
            {
                return View(round);
            }

            if (!round.IsDealerTakes && param == GetActionInGame.NextRound)
            {
                return PartialView(round);
            }

            return View("Error");
        }
    }
}

BlackJack.Web/Controllers/HistoryController.cs
using BlackJack.BusinessLogic.Services.Interfaces;
using BlackJack.ViewModels.Views.HistoryViews;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace BlackJack.Web.Controllers
{
    public class HistoryController : Controller
    {
        private IHistoryService _historyService;
        public HistoryController(IHistoryService historyService)
        {
            _historyService = historyService;
        }

        [HttpGet]
        public async Task<ActionResult> GetAllGames()
        {
            GetAllGamesHistoryView allGames = await _historyService.GetAllGames();
            return View(allGames);
        }

        public async Task<ActionResult> GameDetails(int id)
        {
            GameDetailsHistoryView gameDetails = await _historyService.GameDetails(id);
            return View(gameDetails);
        }
    }
}

BlackJack.Web/Views/Game/CurrentGame.cshtml
@model BlackJack.ViewModels.Views.GameViews.CurrentGameGameView

<div id="currentGame">
    @{Html.RenderPartial("_NextRound", Model);}
</div>

@Scripts.Render("~/bundles/currentGame")
@Scripts.Render("~/bundles/endGame")

BlackJack.Web/Views/Game/StartGame.cshtml
@model BlackJack.ViewModels.Views.GameViews.StartGameGameView

<div class="parent">
    @using (Html.BeginForm("CreateGame", "Game", FormMethod.Post))
    {
        <div class="row">
            <h4>Enter Player</h4>
            <input id="kendoComboBox" name="Name" />
        </div>

        <div class="row">
            <br />
            <h4>Enter Quantity</h4>
            <input id="kendoDropDown" name="Amount" />
        </div>

        <div class="row">
            <br />
            <button id="kendoButton" type="submit">Execute</button>
        </div>
    }
</div>

<script>
        var data= JSON.parse('@Newtonsoft.Json.JsonConvert.SerializeObject(Model.Names)'.replace(/&quot;/g, "\""));
</script>

@Scripts.Render("~/bundles/startGame")

BlackJack.Web/Views/Game/_GameEnd.cshtml
@model BlackJack.ViewModels.Views.GameViews.CurrentGameGameView

<div class="row">
    <div class=" col-md-12">
        <table class="table" border="1">
            <caption>Game End</caption>
            <tr>
                <th>Name</th>
                <th>Role</th>
                <th>State</th>
                <th>Cards</th>
                <th>Points</th>
                <th>Total points</th>
            </tr>
            <tr></tr>
            <tr></tr>
            @foreach (var item in Model.Players)
            {
                <tr>
                    <td>@item.Name</td>
                    @if (item.Role == BlackJack.ViewModels.Enums.PlayerRoleEnumView.Dealer)
                    {
                        <td colspan="2">@item.Role</td>
                    }
                    @if (item.Role != BlackJack.ViewModels.Enums.PlayerRoleEnumView.Dealer)
                    {
                        <td>@item.Role</td>
                    }

                    @if (item.Role != BlackJack.ViewModels.Enums.PlayerRoleEnumView.Dealer)
                    {
                        <td>@item.State</td>
                    }
                    <td>
                        <table align="center">
                            @foreach (var card in item.Cards)
                            {
                                <tr>
                                    <td>@card.Value  @card.Suit</td>
                                </tr>
                            }
                        </table>
                    </td>
                    <td>
                        <table align="center">
                            @foreach (var card in item.Cards)
                            {
                                <tr>
                                    <td>@card.Points</td>
                                </tr>
                            }
                        </table>
                    </td>

                    <td>@item.TotalPoints</td>
                </tr>
                <tr></tr>
                <tr></tr>
            }

        </table>
    </div>
    <div class="col-md-4 col-md-push-1">
        @using (Html.BeginForm("StartGame", "Game"))
        {
            <button id="kendoButtonNewGame" type="submit">New Game</button>
        }
    </div>
    <div class="col-md-4 col-md-push-5">

        @using (Html.BeginForm("GetAllGames", "History", FormMethod.Get))
        {
            <button id="kendoButtonHistory" type="submit">History</button>
        }
    </div>

</div>


@Scripts.Render("~/bundles/endGame")

BlackJack.Web/Views/Game/_NextRound.cshtml
@model BlackJack.ViewModels.Views.GameViews.CurrentGameGameView
@using BlackJack.BusinessLogic.Enums
<div class="row">
    <div class=" col-md-12">
        <table class="table" border="1">
            <caption>Current Game</caption>
            <tr>
                <th>Name</th>
                <th>Role</th>
                <th>Cards</th>
                <th>Points</th>
                <th>Total points</th>
            </tr>
            <tr></tr>
            <tr></tr>
            @foreach (var item in Model.Players)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Role</td>

                    <td>
                        <table align="center">
                            @foreach (var card in item.Cards)
                            {
                                <tr>
                                    <td>@card.Value  @card.Suit</td>
                                </tr>
                            }
                        </table>
                    </td>
                    <td>
                        <table align="center">
                            @foreach (var card in item.Cards)
                            {
                                <tr>
                                    <td>@card.Points</td>
                                </tr>
                            }
                        </table>
                    </td>

                    <td>@item.TotalPoints</td>
                </tr>
                <tr></tr>
                <tr></tr>
            }
        </table>
    </div>

    <div class="col-md-4 col-md-push-2">

        @using (Ajax.BeginForm("CurrentGame", new AjaxOptions { UpdateTargetId = "currentGame", OnSuccess = "OnSuccess", HttpMethod = "Post" }))
        {

            @Html.Hidden("id", Model.GameId);
            GetActionInGame param = GetActionInGame.NextRound;
            @Html.Hidden("param", param);
            <button id="kendoButtonTake" type="submit">Take</button>
        }
    </div>

    <div class="col-md-4 col-md-push-5">

        @using (Html.BeginForm("CurrentGame", "Game", FormMethod.Post))
        {
            @Html.Hidden("id", Model.GameId);
            GetActionInGame param = GetActionInGame.DealerTakes;
            @Html.Hidden("param", param);
            <button id="kendoButtonEnought" type="submit">Enought</button>
        }
    </div>
</div>

@Scripts.Render("~/bundles/currentGame")

BlackJack.Web/Views/History/GameDetails.cshtml
@model BlackJack.ViewModels.Views.HistoryViews.GameDetailsHistoryView
<div class="row">
    <div class=" col-md-12">
        <table class="table" border="1">
            <caption>Game # @Model.GameId</caption>
            <tr>
                <th>Name</th>
                <th>Role</th>
                <th>State</th>
                <th>Cards</th>
                <th>Points</th>
                <th>Total points</th>
            </tr>
            <tr></tr>
            <tr></tr>
            @foreach (var item in Model.Players)
            {
                <tr>
                    <td>@item.Name</td>
                    @if (item.Role == BlackJack.ViewModels.Enums.PlayerRoleEnumView.Dealer)
                    {
                        <td colspan="2">@item.Role</td>
                    }
                    @if (item.Role != BlackJack.ViewModels.Enums.PlayerRoleEnumView.Dealer)
                    {
                        <td>@item.Role</td>
                    }
                    @if (item.Role != BlackJack.ViewModels.Enums.PlayerRoleEnumView.Dealer)
                    {
                        <td>@item.State</td>
                    }
                    <td>
                        <table align="center">
                            @foreach (var card in item.Cards)
                            {
                                <tr>
                                    <td>@card.Value</td>
                                </tr>
                            }
                        </table>
                    </td>
                    <td>
                        <table align="center">
                            @foreach (var card in item.Cards)
                            {
                                <tr>
                                    <td>@card.Points</td>
                                </tr>
                            }
                        </table>
                    </td>
                    <td>@item.TotalPoints</td>
                </tr>
                <tr></tr>
                <tr></tr>
            }

        </table>
    </div>

    <div class="row">
        <div class="col-md-4 col-md-push-4">
            <br />
            <br />
            @using (Html.BeginForm("GetAllGames", "History", FormMethod.Get))
            {
                <button id="kendoButtonBack" type="submit">Back</button>
            }
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/gameDetails")

BlackJack.Web/Views/History/GetAllGames.cshtml
@model  BlackJack.ViewModels.Views.HistoryViews.GetAllGamesHistoryView

<div id="grid">
    <h2>History</h2>
</div>

<script>
     var data = JSON.parse('@Newtonsoft.Json.JsonConvert.SerializeObject(Model.Games)'.replace(/&quot;/g, "\""));
</script>

@Scripts.Render("~/bundles/getallgames")

BlackJack.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2018.2.620/styles/kendo.common.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2018.2.620/styles/kendo.rtl.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2018.2.620/styles/kendo.silver.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2018.2.620/styles/kendo.mobile.all.min.css" />

    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.2.620/js/kendo.all.min.js"></script>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul style="font-size: x-large" class="nav navbar-nav">
                    <li>@Html.ActionLink("New Game", "StartGame", "Game")</li>
                    <li>@Html.ActionLink("History", "GetAllGames", "History")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/scripts/jquery-3.3.1.min.js")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.min.js")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>